version: "2"
services:
  web:
    image: rcoedo/phoenix-elm:0.0.2
    command: mix phoenix.server
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db
    working_dir: /app
    ports:
      - "4000:4000"

  db:
    image: postgres:9.5
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: phoenix_library_dev
    ports:
      - "5432:5432"
